replicaCount: 3

image:
  repository: ghcr.io/shayle664/shay-final-project
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

container:
  port: 5007

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  create: false
  name: ""
automountServiceAccountToken: false
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
