apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shayle664/FinalProject.git
    targetRevision: main
    path: k8s/helm-final-project
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
