apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
  labels:
    app: final-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
        - name: app
          # TODO: change this to your image (Docker Hub or GHCR)
          image: ghcr.io/shayle664/FinalProject:shay-final-project
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5007
          env:
            # examples; delete if not needed
            - name: FLASK_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: 5007
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5007
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: final-project
  labels:
    app: final-project
spec:
  selector:
    app: final-project
  ports:
    - name: http
      port: 80
      targetPort: 5007
  type: ClusterIP
