image:
  repository: ghcr.io/shayle664/shay-final-project
  tag: latest
  pullPolicy: IfNotPresent
  # No pullSecrets needed for public images

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5007

containerPort: 5007

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Security context for public deployments
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

# Optional Ingress (disabled by default)
ingress:
  enabled: false
  className: ""
  hosts:
    - host: shay-final.dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
