apiVersion: v1
kind: Service
metadata:
  name: shay-final-project
  labels:
    app: shay-final-project
spec:
  type: ClusterIP
  selector:
    app: shay-final-project
  ports:
    - name: http
      port: 5007
      targetPort: 5007

