apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-dev
resources:
  - ../../base

images:
  - name: ghcr.io/OWNER/shay-final-project
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: shay-final-project
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

