name: CI - DEV to QA

on:
  pull_request:
    branches:
      - QA

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dummy test
        run: echo "✅ CI pipeline running"

