name: CI (lite)
on:
  push:
    branches-ignore: [main]
  pull_request:

jobs:
  lite:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps (no dev extras if you want even faster)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff black mypy pytest

      # style + lint
      - name: Code style & lint
        run: |
          ruff .           # fast linter
          black --check .  # formatting check

      # type-check
      - name: Type check
        run: mypy .

      # unit tests only (skip slow/integration/e2e)
      - name: Unit tests
        run: pytest -q -m "not e2e and not integration"
