name: CI (lite)
on:
  push:
    branches-ignore: [main]
  pull_request:

jobs:
  lite:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: App
        
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff mypy

      # style + lint
      - name: Code style & lint
        run: |
          ruff format --check .
          ruff check --output-format=github .

      # type-check
      - name: Type check
        run: mypy .
