apiVersion: v1
kind: Service
metadata:
  name: {{ include "final-project.fullname" . }}
  labels:
    {{- include "final-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "final-project.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
