replicaCount: 2

image:
  repository: ghcr.io/shayle664/shay-final-project
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

container:
  port: 5007

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: final.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
